# Generated by Django 5.2.7 on 2025-11-25 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('child', 'Child')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('loci_count', models.IntegerField(default=0, help_text='Number of analyzed loci')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['-uploaded_at'], name='dna_uploade_uploade_b9579d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dna.person')),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dna.uploadedfile')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('person', 'uploaded_file')},
            },
        ),
        migrations.AddField(
            model_name='person',
            name='uploaded_files',
            field=models.ManyToManyField(related_name='persons', through='dna.PersonFile', to='dna.uploadedfile'),
        ),
        migrations.CreateModel(
            name='DNALocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locus_name', models.CharField(choices=[('D1S1656', 'D1S1656'), ('D2S441', 'D2S441'), ('D2S1338', 'D2S1338'), ('D3S1358', 'D3S1358'), ('D5S818', 'D5S818'), ('D6S1043', 'D6S1043'), ('D7S820', 'D7S820'), ('D8S1179', 'D8S1179'), ('D10S1248', 'D10S1248'), ('D12S391', 'D12S391'), ('D13S317', 'D13S317'), ('D16S539', 'D16S539'), ('D18S51', 'D18S51'), ('D19S433', 'D19S433'), ('D21S11', 'D21S11'), ('D22S1045', 'D22S1045'), ('CSF1PO', 'CSF1PO'), ('FGA', 'FGA'), ('TH01', 'TH01'), ('TPOX', 'TPOX'), ('vWA', 'vWA'), ('Penta D', 'Penta D'), ('Penta E', 'Penta E')], max_length=50)),
                ('allele_1', models.CharField(blank=True, max_length=10, null=True)),
                ('allele_2', models.CharField(blank=True, max_length=10, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loci', to='dna.person')),
                ('source_file', models.ForeignKey(blank=True, help_text='Which file added this locus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loci_added', to='dna.uploadedfile')),
            ],
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['role'], name='dna_person_role_8e8888_idx'),
        ),
        migrations.AddIndex(
            model_name='dnalocus',
            index=models.Index(fields=['locus_name'], name='dna_dnalocu_locus_n_1969d4_idx'),
        ),
        migrations.AddIndex(
            model_name='dnalocus',
            index=models.Index(fields=['allele_1', 'allele_2'], name='dna_dnalocu_allele__5e88e0_idx'),
        ),
        migrations.AddIndex(
            model_name='dnalocus',
            index=models.Index(fields=['person', 'locus_name'], name='dna_dnalocu_person__714a3f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dnalocus',
            unique_together={('person', 'locus_name')},
        ),
    ]
